#!/bin/sh
# Author: 1ryuk
# Date: 2021-10-21
#

sib=$(cat /proc/cpuinfo | grep "siblings" | awk NR==1 | awk {'print $3'})
i=0

while true; do
	i=0

	# User information
	echo "Date:" $(date +'(%a) %l:%M:%S %p  %d/%m/%g')
	echo "Uptime:" $(uptime -p | awk {'print $2$3, $4$5, $6$7'})
	echo
	echo "Tasks/Threads:" $( ps -eLf | wc -l)
	echo
	echo "Users:"
	printf "%s\n" "$(who)"
	echo

	# Battery information
	# Battery Charge info
	if [ ! -x /bin/acpi ]; then
		echo "ACPI not found!"
		echo
		echo "Please install the ACPI package to get CPU information"
	else
		echo $(acpi)
	fi

	# Battery wattage
	if [[ -e /sys/class/power_supply/BAT0/power_now ]]; then
		echo $(awk '{print "Watts: " $1*10^-6 " W"}' /sys/class/power_supply/BAT0/power_now)
	elif [[ -e /sys/class/power_supply/BAT1/power_now ]]; then
		echo $(awk '{print "Watts: " $1*10^-6 " W"}' /sys/class/power_supply/BAT1/power_now)
	else
		echo "No battery was detected!"
	fi

	# Battery Voltage
	if [[ -n $(sensors | grep "in0") ]]; then
		echo "Volts:" $(sensors | grep "in0" | awk {'print $2,$3'})
	else
		echo "No battery voltage was detected!"
	fi

	# lm-sensors
	if [ ! -x /bin/sensors ]; then
		echo "ERROR! Sensors not found"
		echo
		echo "Please install the lm-sensors package to get CPU infomation"
	else
		# Fan speed
		if [[ -n $(sensors | grep "fan") ]]; then
			echo
			echo "Fan speed" : $(sensors | grep "fan" | awk {'print $2,$3'})
		else
			echo "Fan not detected!"
		fi

		# CPU temp
		if [[ -n $(sensors | grep "Package") ]]; then
			echo
			echo "CPU Temp" : $(sensors | grep "Package" | awk {'print $4,$5'})
		elif [[ -n $(sensors | grep "CPU") ]]; then
			echo
			echo "CPU Temp" : $(sensors | grep "CPU" | awk {'print $2,$3'})
		elif [[ -n $(sensors -u | grep "temp1_input") ]]; then
			echo
			echo "CPU Temp" : $(sensors -u | grep "temp1_input" | awk {'print $1'})
		else
			echo "No CPU temps were detected!"
		fi

		# CPU temp
		if [[ -n $(sensors | grep "GPU:") ]]; then
			echo "GPU Temp" : $(sensors | grep "GPU:" | awk {'print $2,$3'})
		elif [[ -n $(sensors | grep "GPU Core:") ]]; then
			echo "GPU Temp" : $(sensors | grep "GPU Core:" | awk {'print $2'})
		else
			echo "No GPU temps were detected!"
		fi
	fi

	# Ram information
	echo
	echo "RAM in use:" $(free -h --total | awk 'NR>1 && NR<3{print $3}')
	echo "RAM Free:" $(free -h --total | awk 'NR>1 && NR<3{print $4}')
	echo
	echo "Swap in use:" $(free -h --total | awk 'NR>2 && NR<4{print $3}')
	echo "Swap Free:" $(free -h --total | awk 'NR>2 && NR<4{print $4}')

	# CPU frequencies
	if [[ -n $(cat /proc/cpuinfo | grep "cpu MHz") ]]; then
		echo
		while [ $i -lt $sib ]
		do
			echo "CORE $i" : $(cat /proc/cpuinfo | grep "cpu MHz" | awk NR=="$i+1"{'print $4,"MHz"'})
			i=$((i+1))
		done
	else
		echo "No CPU frequencies were detected!"
	fi

	sleep 3
	clear
done
